language: python

python:
  - "2.7"
  - "3.3"

env:
  global:
    - PYTHONPATH=.
  matrix:
    - DJANGO=Django==1.5.4
    - DJANGO=https://github.com/django/django/archive/1.6b4.zip
    - DJANGO=https://github.com/django/django/archive/master.zip

install:
  - "pip install $DJANGO --use-mirrors"

script:
  - python testproject/manage.py test

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/archive/master.zip
